### ISSUE TITLE
None of the results indicate the type of flight / caravan on the train / the type of bus in which they travel.

### ISSUE THREAD

**Issue by fegyb** [talmantel/CheapTripAngularClient#12]
1.5
19.10.20
FEIGY BEN NHIM  

What is expected to happen: As a user of the system, I would expect to see what type of flight or train car it is so that I can calculate whether the price is really worthwhile.

What is actually happening: None of the results details the type of trip expected of me

We checked through Chrome browsers Firefox Safari 
Explorer Opera and Mobile – Results screen

In software testing on version 0.0.2

Description of the fault detected  :None of the results indicate the type of flight / caravan on the train / the type of bus in which they travel. Need more information about the flights. Is it a business class or a regular class. Which blow is it - near the window or not. The trains do not specify which caravan and whether it is a caravan that also includes a lodging
   

Fault – HIGH

It is better to fix - urgently 

Fault condition - open

What will happen as a result-  The system will not be clear enough

Browse to other places in the system

Where the fault was discovered-  On the Search Results screen under Travel Results

**Comment by OlgaZaleskovskaya** [comment]
Probably this is a problem of information in database. There is no such information like type of flight or caravan.  Such details are not available for today.
