### ISSUE TITLE
When the Hebrew language was chosen for the translation of the site, while typing the city name, it was not possible to type its name in the Hebrew language.

### ISSUE THREAD

**Issue by fegyb** [talmantel/CheapTripAngularClient#14]
4.11
19.10.20
FEIGY BEN NHIM  

What is expected to happen: When translating into Hebrew or another language, typing into Hebrew and other languages will also be possible in the search.

What is actually happening - Even after translation it is still possible to type only in English

We checked through Chrome browsers Firefox Safari 
Explorer Opera and Mobile. No access via Internet Explorer – Discovered while typing cities on main screen. Happens only through the Chrome browser
  

In software testing on version 0.0.2

Description of the fault detected  - When the Hebrew language was chosen for the translation of the site, while typing the city name, it was not possible to type its name in the Hebrew language, these are only in English

Fault- medium 

It is better to fix - urgently 

Fault condition -  open

What will happen as a result -  The user will not be allowed to perform a full search in a language he or she writes other than English 

Where the fault was discovered - Detected on the city search screen at the time of typing

**Comment by rmant7** [comment]
It's OK. Should be closed
