### ISSUE TITLE
The category name does not appear. 

### ISSUE THREAD

**Issue by fegyb** [talmantel/CheapTripAngularClient#15]
4.11 

19.10.20
FEIGY BEN NHIM  

What is expected to happen: Above the category of travel routes if it is all routes The icon of all routes appears, the same in the category only planes and everything except planes

What is actually happening  - No category type information

We checked through Chrome browsers Firefox Safari 
Explorer Opera and Mobile. No access via Internet Explorer – Viewed on city search results screen

In software testing on version 0.0.2

Description of the fault detected - The category name does not appear. The user will not understand the category differences without having its name listed above

Fault- high 

It is better to fix - urgently 

Fault condition – open 

What will happen as a result - Will make it difficult for the user to understand the system

Where the fault was discovered - View search results when travel routes appear in separate categories

**Comment by OlgaZaleskovskaya** [comment]
I donot quite understand your idea.  Could you illustrate it somehome.
