### ISSUE TITLE
It is not stated on the flights whether there is an additional charge for luggage and how much it will cost.

### ISSUE THREAD

**Issue by fegyb** [talmantel/CheapTripAngularClient#16]
5.9
19.10.20
FEIGY BEN NHIM  

What is expected to happen: Details of the flight results regarding cargo should appear 

What is actually happening - There is nothing about luggage on the flight

We checked through Chrome browsers Firefox Safari 
Explorer Opera and Mobile. No access via Internet Explorer – Appears during general travel searches

In software testing on version 0.0.2

Description of the fault detected - It is not stated on the flights whether there is an additional charge for luggage and how much it will cost (in most cases when the flight is cheap the reason is a charge that costs more) 

Fault- high 

It is -not urgent

Fault condition - open

What will happen as a result- It will be difficult for the user to understand how cheap the flight really is or whether it is cheap in an expensive cargo wave  

Where the fault was discovered-  Discovered during a search of two different cities

**Comment by OlgaZaleskovskaya** [comment]
Worth having such details.
