### ISSUE TITLE
 There is a connection between the price of the trip and the travel time in the results. 

### ISSUE THREAD

**Issue by fegyb** [talmantel/CheapTripAngularClient#28]
0.3.4
27.10.20
FEIGY BEN NHIM  

What is expected to happen: Should show the time separately and the price in euros separately

What is actually happening: Connects time to price

We checked through Chrome browsers Firefox Safari 
Explorer Opera Tor and Mobile – Happens only through computer browsers - Chrome, Opera, Safari, Firefox, Tor. Through the mobile this bug did not happen

In software testing on version 0.0.3

Description of the fault detected:  There is a connection between the price of the trip and the travel time in the results. 
   
Fault- medium. 

It is better to fix – urgently. 

Fault condition – open. 

What will happen as a result-  It will not be clear to the user how much the trip costs and how long it will take

Where the fault was discovered: The error was discovered while navigating between two cities in the search results through all the browsers on the computer we tested through them

![Untitled pngPRAICTIME](https://user-images.githubusercontent.com/72548843/97468164-a36df280-194d-11eb-8b9f-b551210586df.png)

![Untitled](https://user-images.githubusercontent.com/72548843/97466031-52f59580-194b-11eb-8e0d-337c185f889d.png)

**Comment by rmant7** [comment]
Fixed
