### ISSUE TITLE
When you type one letter and many more letters that do not create any existing name, the search bar gets stuck and does not disappear

### ISSUE THREAD

**Issue by fegyb** [talmantel/CheapTripAngularClient#31]
0.4.4
29.10.20
FEIGY BEN NHIM  

What is expected to happen: When we create a word that does not exist in the list in the checkbox the list will disappear and not get stuck on the list of existing cities

What is actually happening: The checkbox gets stuck and the list stays on existing cities 

We checked through Chrome browsers Firefox Safari 
Explorer Opera Tor and Mobile – Happened through a Chrome browser on your computer

In software testing on version 0.0.4

Description of the fault detected: In the search field in the Chrome browser on the computer. When you type one letter and many more letters that do not create any existing name, the search bar gets stuck and does not disappear
   

Fault- Low

It is better to fix –Not urgently.

Fault condition – open. 

What will happen as a result-  The system does not command like all systems that have a standard checkbox

Where the fault was discovered: Detected during manual software testing through a Chrome browser on the computer

![Untitled pngkk](https://user-images.githubusercontent.com/72548843/97619615-19935780-1a29-11eb-8953-382069f124f1.png)

**Comment by rmant7** [comment]
Fegy, we doesn't allow invalid input. Please, close
