### ISSUE TITLE
When trying to type the names of the cities in the search bar, in case I typed a letter that creates a name of a non-existent city, a message pops up.   

### ISSUE THREAD

**Issue by fegyb** [talmantel/CheapTripAngularClient#32]
0.4.3
29.10.20
FEIGY BEN NHIM  

What is expected to happen: When we type letters of non-existent cities, an error window will not pop up. Instead the search field simply disappears the other options since none of them match the typing

What is actually happening: The system pops up an entire error window just because I typed the beginning of a name that does not exist in the list

We checked through Chrome browsers Firefox Safari Explorer Opera Tor and Mobile – Happened only through Chrome browser on mobile.

In software testing on version 0.0.4

Description of the fault detected : Chrome browser in mobile - When trying to type the names of the cities in the search bar, in case I typed a letter that creates a name of a non-existent city, a message pops up. The message says - An error has occurred! There is no cheap way to get there.
   

Fault- very high. 

It is better to fix – urgently. 

Fault condition – open. 

What will happen as a result-  The user will not understand what is wanted from him. This window is completely unnecessary

Where the fault was discovered: During manual software testing via Chrome browser on Mobile

![image_123986672 (12)](https://user-images.githubusercontent.com/72548843/97619970-91fa1880-1a29-11eb-8e88-287ef80cf1f1.JPG)

**Comment by rmant7** [comment]
Fegy, it's ok. Close
