### ISSUE TITLE
The search field to does not complete the name of the city

### ISSUE THREAD

**Issue by fegyb** [talmantel/CheapTripAngularClient#34]
0.4.6
2.11.20
FEIGY BEN NHIM  

What is expected to happen: A list of cities that start with the same letter we typed or that include the letter should open.

What is actually happening: The list does not open The system does not respond to random letters that are typed

We checked through Chrome browsers Firefox Safari 
Explorer Opera Tor and Mobile – Happens via mobile

In software testing on version 0.0.4

Description of the fault detected: Via the mobile (Safari and Chrome) The search fiel “to” does not complete the name of the cities when you type the first letter

   

Fault- very high. 

It is better to fix – urgently. 

Fault condition – open. 

What will happen as a result-  The system does not allow convenient search for those who use it

Browse to other places in the system. Moved to the “from” button

Where the fault was discovered: Discovered via Safari and Chrome while searching via mobile in an attempt to type letters in the search field

![image_123986672 (16)](https://user-images.githubusercontent.com/72548843/97917415-1b2c8a80-1d5d-11eb-9869-108d6643c7fb.JPG)

**Comment by OlgaZaleskovskaya** [comment]
We had some problems with server. Now it is fixed
