### ISSUE TITLE
Client User Interface - Title

### ISSUE THREAD

**Issue by Seva-SQL** [talmantel/CheapTripAngularClient#39]
I suggest adding a product name and slogan to the start page.

![2020-11-04 134117](https://user-images.githubusercontent.com/73934063/98113632-3f46b380-1ea4-11eb-8d5c-ec1687a20cd1.png)

**Comment by rmant7** [comment]
In addition, please change
meta name="Description" content="Discover the cheapest way at lowcoststrip.com -for plane, train, bus and rideshare"
to
meta name="Description" content="Discover the cheapest way to get anywhere combining plane, train, bus and rideshare at lowcoststrip.com"

**Comment by OlgaZaleskovskaya** [comment]
done
