### ISSUE TITLE
There is not enough information in the results 

### ISSUE THREAD

**Issue by fegyb** [talmantel/CheapTripAngularClient#9]
name: feigy ben nhim
date: 15/10/20

In the search results stage after booking two cities (no matter which cities) the results do not show where you can take the bus, train, flight. 

Tested via Mobile (iPhone 11)
Tested through Windows 10 Firefox browser and Chrome browser
Tested via Mac 2011 version via Safari Chrome and Firefox browser
Tested through virtualization installed on Windows 10

Discovered in version number 0.0.2

Fault severity is considered to be a high severity fault

Priority for high priority correction

Open fault

If this bug is implemented the future user will not have the option to use the results that the system will give him

This bug can affect search results in terms of price order and visibility across the screen

 
![image_123986672(1)](https://user-images.githubusercontent.com/72548843/96118482-3b9ebd00-0ef4-11eb-9734-9d3297b0009e.JPG)

**Comment by OlgaZaleskovskaya** [comment]
Unfortunatelly such information is not available for me
